### ISSUE TITLE
“rem.app” is damaged and can’t be opened. You should eject the disk image.

### ISSUE THREAD

**Issue by vladstudio** [jasonjmcghee/rem#1]
<img width="324" alt="image" src="https://github.com/jasonjmcghee/rem/assets/914320/d76eab4f-757b-4649-93a1-3ac516cf14bd">

Just thought I'd let you know that I cannot open the app on M1 Macbook Air.

  Model Name:	MacBook Air
  Model Identifier:	MacBookAir10,1
  Model Number:	MGN63RU/A
  Chip:	Apple M1
  Total Number of Cores:	8 (4 performance and 4 efficiency)
  Memory:	8 GB
  System Firmware Version:	10151.61.4
  OS Loader Version:	10151.61.4
  Serial Number (system):	C02DP9EMQ6L4
  Hardware UUID:	2F02303C-6478-55AD-80EA-0EFE3AAFB5DC
  Provisioning UDID:	00008103-001D29322E62001E
  Activation Lock Status:	Enabled

**Comment by jasonjmcghee** [comment]
Thank you! I will try to figure out why that is. Sorry about that!

**Comment by jasonjmcghee** [comment]
Looks like it currently requires `xattr -c rem.app` - I'll work on fixing that

**Comment by vladstudio** [comment]
> Looks like it currently requires `xattr -c rem.app` - I'll work on fixing that

that helped, thanks!
