### ISSUE TITLE
No output files, ffmpeg trace trap.

### ISSUE THREAD

**Issue by dollarusername** [jasonjmcghee/rem#105]
After grabbing 0.1.14 it works fine on one M2 Pro mac running Sonoma, however on another host it doesn't collect any data.
The ffmpeg binary gives a trace trap when running:
./ffmpeg.orig
[1]    97323 trace trap  ./ffmpeg.orig

I've replaced the binary with a working one from homebrew, however I still don't get any data other than the DB files-- no video dumped at all.  Fulls screen permissions have been set.  Am on a multi-monitor setup.
Copies context correctly.

Any ideas?

**Comment by dollarusername** [comment]
Oops, it appears on my working host ffmpeg does the same trace trap, and that one works correctly.  I'll move it back in place and see if I can figure out why it's not working.

**Comment by jasonjmcghee** [comment]
What are the specs of the other host machine? (Also Sonoma + M2?)

**Comment by jasonjmcghee** [comment]
Can you check this thread and see if it describes your issue / the same workaround works?

https://github.com/jasonjmcghee/rem/issues/99

We need to figure out how to fix this issue. It seems to happen on first launch if the MacBook display isn't being used.

**Comment by dollarusername** [comment]
Yes I checked #99 and that was how I got it to work.  Disconnected all monitors, set the options and it's now working great.
This system is Sonoma and M1.

**Comment by dollarusername** [comment]
I noticed it only seems to capture content on my external monitor, not on the laptop display.

**Comment by jasonjmcghee** [comment]
closing in favor of #99
