### ISSUE TITLE
Not Remembering on Mac Mini

### ISSUE THREAD

**Issue by qwertyus124** [jasonjmcghee/rem#109]
I'm having an issue on an M2 Pro Mac Mini with a displayport monitor. I'm seeing "nothing to remember" in the timeline view and nothing at all in the search view. "Show my data" shows a bunch of 0byte mp4 files.Purging and reinstalling/restarting hasn't worked, and neither has removing and readding permissions.

**Comment by jasonjmcghee** [comment]
I'm going to close in favor of #99 but I hear you that you cannot use the workout in #99 (which is still a problem).

I'll spend some time looking into a fix for this - a bit difficult for me as I don't have a mac mini, so can't directly reproduce the same conditions, but hoping doing a real fix for #99 with fix it.
