### ISSUE TITLE
Icon looks kinda weird [relatively] when active in dark mode?

### ISSUE THREAD

**Issue by ruslanjabari** [jasonjmcghee/rem#11]
<img width="755" alt="Screenshot 2023-12-28 at 7 12 35 PM" src="https://github.com/jasonjmcghee/rem/assets/59275080/9fda125e-8006-4add-a1ba-0423cb80d27f">

This probably slipped through the cracks since the Loom demo was in light mode lol

**Comment by jasonjmcghee** [comment]
I am in dark mode, I think that's based on your background picture.

What's the right way to make this icon? Is there some monochrome approach that inverts appropriately?

Happy to make inverted versions of the status icons. do you know how to make theme specific icons?

**Comment by ruslanjabari** [comment]
My lazy approach is to normally just create two versions (inverted colors) and match them to the theme of the system.

There's a bunch of ways to detect whether the system is in dark or light mode: https://stackoverflow.com/questions/25207077/how-to-detect-if-os-x-is-in-dark-mode

**Comment by jasonjmcghee** [comment]
Doesn't seem to have anything to do with light / dark mode


https://github.com/jasonjmcghee/rem/assets/1522149/7ae80d61-9d89-4939-9be8-b69d0cb748d7

**Comment by jasonjmcghee** [comment]
Answer seems to be this: https://stackoverflow.com/a/64525038
