### ISSUE TITLE
Product > Archive only produces SQLite iOS

### ISSUE THREAD

**Issue by robfentress** [jasonjmcghee/rem#110]
I don't develop in XCode, so I'm probably overlooking something obvious.  However, when I follow your build instructions and choose Product > Archive, the only thing generated is "SQLite iOS" and there is no "Distribute App" button, just "Distribute Content".  What am I doing wrong?

**Comment by jasonjmcghee** [comment]
I see you closed this before I had a chance to look at it! I believe you just need to choose your Mac as the target, manually. My recollection is that it's a default of Sqlite.swift and we'd need to fork it to change it. If that's not the case, please let me know!

And if you this was not the fix, please feel free to share what you did to fix it for yourself, so others can see it in the future!
