### ISSUE TITLE
Build error: error: Build input file cannot be found: '/Users/kurt/GitHub/rem/rem/SettingsManager.swift'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it? (in target 'rem' from project 'rem')

### ISSUE THREAD

**Issue by kurtseifried** [jasonjmcghee/rem#2]
Steps to reproduce:

1. Install Xcode on a Mac M1
2. Add GitHub account
3. Add Apple account and enable signing for personal team; let Xcode manage it
4. Fork rem repo (kurtseifried/rem)
5. Open project, clone git repo kurtseifried/rem
6. Import SQLite from https://github.com/stephencelis/SQLite.swift
7. Clean build folder to be on the safe side
8. Hit build, get error:

error: Build input file cannot be found: '/Users/kurt/GitHub/rem/rem/SettingsManager.swift'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it? (in target 'rem' from project 'rem')

Am I missing something obvious here?

**Comment by jasonjmcghee** [comment]
@kurtseifried - sorry... tried to get that settings feature in too quickly. should be fixed

**Comment by jasonjmcghee** [comment]
Marking as fixed... let me know if it doesn't work after that.

**Comment by kurtseifried** [comment]
This part works but now I'm getting a consistent SQLite error (which it wasn't doing before, weird). 

swift xcode /Users/kurt/GitHub/rem/rem.xcodeproj This Copy Files build phase contains a reference to a missing file 'SQLite.framework'.

**Comment by kurtseifried** [comment]
Oh I appear to have broken my code signing again. nevermind.

**Comment by jasonjmcghee** [comment]
Do feel free to open a PR and improve my shoddy instructions! Apologies for not including any and all key steps
