### ISSUE TITLE
Add option to Disable/Customize Shortcut

### ISSUE THREAD

**Issue by jarrenrocks** [jasonjmcghee/rem#21]
I use Figma and regularly use CMD+Scroll to navigate the canvas, it seems like it activates the timeline which means I can't use this at the same time as figma.

**Comment by jasonjmcghee** [comment]
Sure!

**Comment by jasonjmcghee** [comment]
It'll be in the next build... maybe i'll cut one now, for this and light/dark mode fix

**Comment by jarrenrocks** [comment]
Sounds great! I'm happy to give feedback whenever I get a chance, I used Rewind pretty heavily for a few months and was waiting for someone to open source a version. Thanks for taking the initiative 🙏 (wouldn't be surprised to see Apple add this as a default function in macOS eventually)

**Comment by jasonjmcghee** [comment]
Excited to disappoint you! 😄 Don't hesitate to report any and all bugs and thorns. I'd love to get it stable.
