### ISSUE TITLE
Pressing escape should dismiss the search and timeline functions if you haven't clicked on the screen yet.

### ISSUE THREAD

**Issue by jarrenrocks** [jasonjmcghee/rem#24]
Currently, if you activate the timeline or the search and press escape, you're not able to dismiss it until you click on the window and then you can dismiss it. Ideally, it should be able to be dismissed right away just by pressing escape without having to select the window first.

**Comment by jasonjmcghee** [comment]
Something must be going wrong with the way windows are being made "key" / ordered.

This would be a great self-contained issue for someone to tackle!

**Comment by jarrenrocks** [comment]
Fixed in 0.1.6
