### ISSUE TITLE
Settings Window Does Not Use MacOS Standard

### ISSUE THREAD

**Issue by seletz** [jasonjmcghee/rem#39]
It seems to me that the current settings implementation does not use the standard MacOS UI for settings.

Pressing CMD-, should open application settings, this opens a empty window instead.

This should be an easy fix -- at least in my ObjC days it was pretty simple to add a standard settings window.  I might try to get this going, no promises, though -- I've not be doing MaxOS UI development for a very long time.  I'll see how this goes.

**Comment by seletz** [comment]
See also #38

**Comment by jasonjmcghee** [comment]
Definitely winged it here, didn't realize there's an official route.

Are there any downsides, like a rigid interface to add settings etc.?

Do you have a documentation link?

**Comment by caetano-dev** [comment]
I opened a PR for this! Check #42
