### ISSUE TITLE
Skip processing identical screens

### ISSUE THREAD

**Issue by lotas** [jasonjmcghee/rem#50]
I noticed that videos and search returns quite a lot of similar images which are not worth recording and OCRing.

Probably the trick here is to detect how much has changed between frames. But this could potentially save lots of processing resources and make disk footprint smaller.

**Comment by jasonjmcghee** [comment]
Agree on UX front.

We could likely do a diff against the last and if it's within some tolerance, don't OCR.

Curious how much we'd actually save on disk - h264 is damn good at diffing.

**Comment by lotas** [comment]
I'm not sure about video, but I see that in db there are also multiple similar documents recorded one after another.

There is probably some value to still record time and the fact that contents didn't change, in case there are plans to extract that information into some stats. I mean it would be easy to show how much time was spent per app or so, and for this knowing the app was active is still important. 
But for storage purposes similar content could be avoided.

just some ideas :) thanks
