### ISSUE TITLE
Venture 13.1 can't open it? (Blocked icon)

### ISSUE THREAD

**Issue by oujii** [jasonjmcghee/rem#52]
Hello!

I can't seem to open the app at all, do I need Sonoma?
Thanks!

<img width="380" alt="Screenshot 2024-01-02 at 01 29 13" src="https://github.com/jasonjmcghee/rem/assets/15253421/e01cfc3f-84f2-42c8-bfa7-e0d4cb4e7f9a">

**Comment by jasonjmcghee** [comment]
I had been building 14+. I’ll cut a new one at 13 and post it here

**Comment by oujii** [comment]
Brilliant Jason, thank you! It works like a charm!
