### ISSUE TITLE
Make a real official signed build

### ISSUE THREAD

**Issue by jasonjmcghee** [jasonjmcghee/rem#6]

**Comment by ruslanjabari** [comment]
Are you considering putting it on TestFlight for beta testing as well?

**Comment by jasonjmcghee** [comment]
I think we should be able to make a build that doesn't require someone to disable gatekeeper.

Currently building arm64 static `ffmpeg` - going to swap that out first, then see if i can figure out how to sign it properly so that we can get through the hardened runtime.

**Comment by jasonjmcghee** [comment]
Haven't figured out how to sign it properly yet, but wow was that worth it. DMG is < 3MB now and it's native arm64 performance now.

**Comment by jasonjmcghee** [comment]
Yes!!! It works!
