### ISSUE TITLE
Animated wallpaper causes CPU/battery drain even when not recording

### ISSUE THREAD

**Issue by roblg** [jasonjmcghee/rem#66]
I haven't had a chance to dig into this much, but I was running a debug build of `rem` that was _not_ set to remember anything. And I happened to check the battery drain:

<img width="320" alt="image" src="https://github.com/jasonjmcghee/rem/assets/777138/db07a0d3-5d91-4ef1-9f26-579a8f7c13ba">

I checked activity and the rem process was pulling 100% doing...something? Not sure what.

Tossing here in case someone else sees same behavior w/ more details.

edit: fyi my was based on 4ea0929c30adb3d15483d246c88b176b0d7c228f with no local changes.

**Comment by jasonjmcghee** [comment]
Oh no! Thank you for seeing this. Very, very curious what that could be! I definitely haven't seen this behavior.

Please do feel free to investigate. Would be an awesome change to fix whatever this might be.

**Comment by jasonjmcghee** [comment]
If anyone can reproduce this / sees this, I’d be very interested. Tried quite a bit of different things to get this to happen and haven’t been able to.

**Comment by roblg** [comment]
It's reproducible for me. I get rem pegged at 100% just by running the app (from XCode, if you think that makes a difference)

M2 MBA 15", Sonoma, laptop display (in case that matters)

I hooked it up to the XCode profiler. Would share, but it's 360MB gzip-compressed. I'll post some screenshots of the cpu graphs though.  It seems to be... drawing something, maybe?

<img width="1034" alt="image" src="https://github.com/jasonjmcghee/rem/assets/777138/17d0e5a3-46d0-4736-b5db-d039b46f1cad">

**Comment by roblg** [comment]
all the execution on the main thread: 
<img width="1162" alt="image" src="https://github.com/jasonjmcghee/rem/assets/777138/ecae6ddc-cbba-4e94-ac7d-e46dc57b2b10">

**Comment by jasonjmcghee** [comment]
Can you try disabling this?

https://github.com/jasonjmcghee/rem/blob/a92bfbd68582e42380e21896da13524ef7741302/rem/remApp.swift#L110

do you have an animated background?

**Comment by roblg** [comment]
That appears to have fixed it and yes, it's the default Sonoma background. (Although I didn't realize it was still animating while I had a full-screen window 😬
