### ISSUE TITLE
Ability to disbable timeline?

### ISSUE THREAD

**Issue by digital-cuttlefish** [jasonjmcghee/rem#83]
From what I can see, videos are taken for the timeline feature and screenshots are taken for the search feature.

I can imagine some folks would worry about the memory implications of taking small videos every 2 seconds, especially if they don't use timeline. Maybe it should be disable-able?

**Comment by jasonjmcghee** [comment]
It's all screengrabs to videos to maximize storage efficiency. Timeline and search are two different ways to access the same data.

**Comment by andersonaddo** [comment]
Oh! Makes sense, thanks.
