### ISSUE TITLE
Store Locations of OCR Results in Database

### ISSUE THREAD

**Issue by cparish312** [jasonjmcghee/rem#87]
Plan is to create a a new table "frames_text" with columns (frame_id, text, x, y, w, h)

Considerations:
1) Could make it a Virtual Table to allow FTS4
2) Could replace (or migrate) allText table and replicate current functionality using new table. Without combining the text bounding boxes this could limit search results.

**Comment by jasonjmcghee** [comment]
Seems pretty reasonable! Curious what kind of performance improvement this brings!
