### ISSUE TITLE
Display ID: 1 when second monitor in fullscreen mode

### ISSUE THREAD

**Issue by cparish312** [jasonjmcghee/rem#91]
The display id is 1 and the main monitor screen is captured when the external monitor is in fullscreen. The Active Application is still the correct application.

**Comment by jasonjmcghee** [comment]
Clearly I'm sense- can you attempt to explain the issue a second time / ramifications of the above?

**Comment by cparish312** [comment]
Haha yeah no worries! 

The main result of the bug is when a external monitor is in full screen mode, the contents of that monitor will not be captured even if the active application is the one on the monitor. The below screenshot is the result of fullscreening the firefox window on the external monitor. The Active Application is still firefox, but the display id being recorded is now 1 (which is the main monitor). Leaving fullscreen immediately fixes the isssue. 
![Screenshot 2024-04-29 at 2 17 56 PM](https://github.com/jasonjmcghee/rem/assets/54302513/0349d70c-d2fe-4f36-8a85-7729b07be2d8)

**Comment by cparish312** [comment]
It seems like this is due to a strange behavior of `NSScreen.main?`. 

I'm thinking a robust solution would be to just take the display that the users mouse is currently on. I believe that is rewind's approach.
